name: Build n' Test

on: [ push, pull_request, workflow_call ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download skins
        uses: actions/checkout@v7
        with:
          repository: bemanisoundteam/Cubed-Skins
          path: Cubed-Skins/
          sparse-checkout-cone-mode: /Skins/

      - name: Move skins to bundled resources
        run: mv Cubed-Skins/Skins osu.Game.Rulesets.Cubed/Resources/

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore osu.Game.Rulesets.Cubed.Tests

      - name: Build
        run: dotnet build -c Release --no-restore osu.Game.Rulesets.Cubed.Tests

      - name: Test
        run: dotnet test -c Release --no-build --nologo --verbosity normal osu.Game.Rulesets.Cubed.Tests

      - name: Upload built artifact
        uses: actions/upload-artifact@v7
        with:
          path: osu.Game.Rulesets.Cubed.Tests/bin/Release/net8.0/osu.Game.Rulesets.Cubed.dll
          if-no-files-found: 'error'
          archive: 'false'
